- core/src/main/scala/com/banno/vault/transit/Base64.scala
- core/src/main/scala/com/banno/vault/transit/Transit.scala
- core/src/main/scala/com/banno/vault/transit/models.scala
- core/src/test/scala/com/banno/vault/VaultSpec.scala
- core/src/test/scala/com/banno/vault/transit/MockTransitService.scala
- core/src/test/scala/com/banno/vault/transit/ModelsSpec.scala
- core/src/test/scala/com/banno/vault/transit/TransitGenerators.scala
- core/src/test/scala/com/banno/vault/transit/TransitSpec.scala
Continues from #51.
[Vault Transit](https://www.vaultproject.io/docs/secrets/transit/index.html) is a secrets engine that provides "encryption as a service": it allows creating (on the server) encryption keys with a specific algorithm, and offers an HTTP API with endpoints to encrypt or decrypt data, relieving client from the need to handle keys (which is risky) or implement cryptosystems (which is error-prone). 
In this Pull Request, we add support for transit endpoints. In particular:
- We add a transit-client class, made of a HTTP Client, a key name, and the vault base URI. The ideal use of this Transit-Client is as a representation of a transit connection, which hides all of the transit logic and only provides encryption/decryption functions.
- In line with the design of the Vault …
> Add Vault-Transit client support.

- core/src/main/scala/com/banno/vault/transit/Transit.scala
- core/src/main/scala/com/banno/vault/transit/models.scala
- core/src/test/scala/com/banno/vault/transit/MockTransitService.scala
- core/src/test/scala/com/banno/vault/transit/ModelsSpec.scala
- core/src/test/scala/com/banno/vault/transit/TransitGenerators.scala
- core/src/test/scala/com/banno/vault/transit/TransitSpec.scala
Vault Transit endpoints to encrypt and decrypt data allow for a batch-input mode, in which multiple plaintexts (accompanied or not by a context) may be given in a single go and decrypted, using a single
round-trip for the operation.
This Pull Request adds support in the `transit` package for batched decrypt and encrypt operations. Unlike the single-input variants, that either succeed or fail, a batched request may succeed for some inputs but fail for others. Thus, we need to expose the TransitError case class outside.
We also extend the documentation of the other functions, and we add into the error some context for the operation that failed.
> Transit: Batch encrypt and decrypt

- build.sbt
The build for the versions 5.2.0 has been failing because of a bug in MIMA, described  in https://github.com/lightbend/mima/issues/432.
To avoid falling into that bug, we add exclusion filters.
> Build: add MIMA exclusions to by-pass known bug

- core/src/main/scala/com/banno/vault/transit/models.scala
Since this case class is exposed outside in API, we need
to make it visible to the users and not package-private.
> Open visibility of the TransitError class.

- core/src/main/scala/com/banno/vault/transit/Transit.scala
- core/src/main/scala/com/banno/vault/transit/models.scala
- core/src/test/scala/com/banno/vault/transit/MockTransitService.scala
- core/src/test/scala/com/banno/vault/transit/ModelsSpec.scala
- core/src/test/scala/com/banno/vault/transit/TransitGenerators.scala
- core/src/test/scala/com/banno/vault/transit/TransitSpec.scala
At present, running with an empty list of inputs will produce a raise error (because there is no Right answer). To correct this, and for the optimisation of avoiding unneeded calls, we add a short-cut to end quick on an empty list of inputs.
> Transit Batch endpoints: short-cut on empty list of inputs.

- core/src/main/scala/com/banno/vault/transit/Base64.scala
- core/src/main/scala/com/banno/vault/transit/models.scala
Due to https://github.com/hashicorp/vault/issues/6140, sometimes
we may get a response in which the plaintext is missing field,
which happens if it would have been an empty string.
> Adjust decoder of DecryptResponse, to accept optional plaintext.

- core/src/main/scala/com/banno/vault/transit/Transit.scala
- core/src/test/scala/com/banno/vault/transit/MockTransitService.scala
We were trying to decode `{ "batch_results" : [] }` while the response is `{ "data": { "batch_results" : [] } }`.
> Fix transit batch encryption response decoding

- core/src/main/scala/com/banno/vault/transit/models.scala
When we built the decoder, we did it based on some experiments we run. 
Unfortunately, the Transit API docs do not specify all the fields we saw.
https://www.vaultproject.io/api-docs/secret/transit#read-key
> Fix: decode key details

- core/src/main/scala/com/banno/vault/Vault.scala
- core/src/test/scala/com/banno/vault/VaultSpec.scala
The library currently will output the data from Vault if decoding fails, which will print out secret data, and will likely have it
written to logs. This should hide that value by changing the message of the resulting `InvalidMessageBodyFailure` error.
> Avoid echoing vault value on a decoding error

- core/src/main/scala/com/banno/vault/Vault.scala
- core/src/main/scala/com/banno/vault/models/VaultKeys.scala
- core/src/test/scala/com/banno/vault/VaultSpec.scala
For https://banno-jha.atlassian.net/browse/PUP-1525.
Uses GET version with query param list=true vs using LIST http method.
https://www.vaultproject.io/api-docs#api-operations
https://www.vaultproject.io/api/secret/kv/kv-v1#list-secrets
related https://github.com/Banno/vault4s/pull/206
> add list secrets functionality, which returns keys given a path (main)

- .github/workflows/ci.yml
- build.sbt
- core/src/main/scala/com/banno/vault/Vault.scala
- core/src/main/scala/com/banno/vault/transit/Transit.scala
- core/src/main/scala/com/banno/vault/transit/models.scala
- core/src/test/scala/com/banno/vault/VaultArbitraries.scala
- core/src/test/scala/com/banno/vault/VaultSpec.scala
- core/src/test/scala/com/banno/vault/transit/TransitSpec.scala
- Fixed formatting where needed for Scala3
- Changed use of http4s uri for scala3
- Made type of implicits explicit.
- Changed any deprecation's to match whats in main.
- updated munit for scala 3
Also fixed #163 
See also #214 for update in main.
> seires/8.x Scala3

- .github/workflows/ci.yml
- build.sbt
In Series/8.x we found that the way this is setup we'll hit a case where we end up skipping over 2.13 because of how things are defined.  This enforces usage of ThisBuild.  
```
scalaVersion depends on crossScalaVersions, and then crossScalaVersions is later reset from scalaVersion.
10:21
And we’ve already introduced one mistake: 2.12.12 vs. 2.12.14.  But those generate binary compatible artifacts so nobody really notices.
10:21
And only by virtue of Scala213 being last does a 2.13 remain in the cross builds, so the landmine goes untriggered.
10:22
And now in series/8.x, we append a Scala3 to the end.  Now scalaVersion is 3.0.0.  But we’ve still got that weird redefinition.
10:22
And :boom: We’ve lost Scala 2.13.```
> Rework commonSettings crossScalaVersion override

- .github/workflows/ci.yml
- build.sbt
The same fix as https://github.com/Banno/vault4s/pull/218 just moved forward from 6.x to 7.x.
> Merging forward from 6.x into 7.x (crossscalaversion fix)

- build.sbt
http4s-0.23 got skipped.  vault4s-9.x should use http4s-0.23.
> Downgrade to http4s-0.23.0-RC1

- build.sbt
- core/src/test/scala/com/banno/vault/MissingPieces.scala
- core/src/test/scala/com/banno/vault/VaultSpec.scala
Eliminates all the nasty `unsafeRunSync()`s in the tests.
Features missing in scalacheck-effect are ported in `MissingPieces`.  These could be integrated into scalacheck-effect to partially resolve https://github.com/typelevel/scalacheck-effect/issues/7.
> Use scalacheck-effect

- build.sbt
- core/src/test/scala/com/banno/vault/VaultSpec.scala
The values were being silently discarded by MUnit because we mixed in the wrong stack.
> Run the properties!!!

- build.sbt
These were inherited from before 8.x, and we have a chance to clear the deck.
> Absolve our old binary compatibility sins

- .github/workflows/ci.yml
- build.sbt
sbt-microsites 1.x [requires jekyll 4.0.0 or newer].  Upgrade to fix the missing CSS files.
Before:
After:
[requires jekyll 4.0.0 or newer]: https://47degrees.github.io/sbt-microsites/docs/troubleshooting/
> use jekyll 4.x with sbt-microsites to fix missing styles

- core/src/main/scala/com/banno/vault/Vault.scala
- core/src/test/scala/com/banno/vault/VaultSpec.scala
Adds a companion for `loginAndKeepSecretLeased` that uses the `kubernetes` login.
> Adding a convenience method for login via k8s and keep secret leased.

- .github/workflows/ci.yml
- build.sbt
When MiMa was disabled on the root module, that prevented `TypelevelSonatypeCiReleasePlugin` from adding the `tlCiRelease` command to `commands`, even though it was still generated into the YAML.
Now it's there:
```
sbt:vault4s> show commands
[info] core / commands
[info] 	List(SimpleCommand(git), SimpleCommand(sonatypeBundleRelease), SimpleCommand(sonatypeBundleUpload), SimpleCommand(sonatypePrepare), SimpleCommand(sonatypeOpen), SimpleCommand(sonatypeClose), SimpleCommand(sonatypePromote), SimpleCommand(sonatypeDrop), SimpleCommand(sonatypeRelease), SimpleCommand(sonatypeClean), SimpleCommand(sonatypeReleaseAll), SimpleCommand(sonatypeDropAll), SimpleCommand(sonatypeLog), SimpleCommand(sonatypeStagingRepositoryProfiles), SimpleCommand(sonatypeStagingProfiles), …
```
> Fix publishing

- build.sbt
The next release tag will fail without this.
> Use the legacy Sonatype host

- core/src/main/scala/com/banno/vault/Vault.scala
- core/src/test/scala/com/banno/vault/VaultSpec.scala
1. Handle non-200 successes
2. Attempt recovery if the body is malformed/omitted
Addresses #392
> Make generateSecret more robust

- .github/workflows/ci.yml
- build.sbt
scalac-compat-0.1 via sbt-typelevel-0.5 is pulling in an old Scala 2 library.
> Ignore compile-time scope on dependency submission

- build.sbt
- core/src/main/scala/com/banno/vault/Vault.scala
- core/src/main/scala/com/banno/vault/VaultClient.scala
- core/src/main/scala/com/banno/vault/models/VaultConfig.scala
- core/src/test/scala/com/banno/vault/VaultSpec.scala
Adds support for:
- GitHub token (I needed this for local development)
- Username and Password (resurrects #405)
- AppRole with secret_id (resurrects #303)
Fixes #302
> Support additional login types

- core/src/main/scala/com/banno/vault/Vault.scala
- core/src/main/scala/com/banno/vault/VaultClient.scala
- core/src/main/scala/com/banno/vault/models/VaultApiError.scala
- core/src/main/scala/com/banno/vault/models/VaultRequestError.scala
- core/src/test/scala/com/banno/vault/VaultClientSpec.scala
- core/src/test/scala/com/banno/vault/VaultSpec.scala
This is best-effort, so downstream should probably not build logic around it. Hopefully this will make logs more useful.
Fixes #345
> Report API errors in generated exceptions
