Banno/vault4s

core/src/main/scala/com/banno/vault/transit/Transit.scala

Don't uri encode the key in the transit endpoints.

Fix transit uris

---

core/src/main/scala/com/banno/vault/transit/Transit.scala
core/src/main/scala/com/banno/vault/transit/models.scala
core/src/test/scala/com/banno/vault/transit/MockTransitService.scala
core/src/test/scala/com/banno/vault/transit/ModelsSpec.scala

`"batch_results"` is one more level down below `"data"`.

Fix decoder for batch decrypt

---

core/src/main/scala/com/banno/vault/Vault.scala

The methods `readSecretAndRetain` and `loginAndKeep` include a call to revoke the token or secret lease, at the end of the respective streams method. This is a resource cleanup. However, for some people this may fail. Since this may not be relevant, we add an option, to ignore errors during cleanup.

Ignore errors when revoking the lease.

---

core/src/main/scala/com/banno/vault/Vault.scala

The methods `readSecretAndRetain` and `loginAndKeep` include a call to revoke the token or secret lease, at the end of the respective streams method. This is a resource cleanup. However, for some people this may fail. Since this may not be relevant, we add an option, to ignore errors during cleanup.
(cherry picked from commit 91ddf7341425932c378642083d12060fc83b730c)

Ignore errors when revoking the lease. (#92)

---

.gitignore
core/src/main/scala/com/banno/vault/Vault.scala
core/src/main/scala/com/banno/vault/models/VaultSecret.scala
core/src/test/scala/com/banno/vault/VaultSpec.scala

VaultSecretRenewal May Not be present on all secrets.

Optional VaultSecretRenewal

---

build.sbt
core/src/test/scala/com/banno/vault/VaultSpec.scala
core/src/test/scala/com/banno/vault/transit/ModelsSpec.scala
core/src/test/scala/com/banno/vault/transit/TransitSpec.scala

Fixes: https://github.com/Banno/vault4s/issues/162
This is in preparation for supporting CE3 and Scala 3

Switch to Munit

---

build.sbt
core/src/main/scala/com/banno/vault/Vault.scala
core/src/main/scala/com/banno/vault/transit/Transit.scala
core/src/test/scala/com/banno/vault/VaultSpec.scala
core/src/test/scala/com/banno/vault/transit/MockTransitService.scala

Upgrades to 0.22-M5 http4s.  
This will become series/8.x

Upgrade to 0.22-m5 http4s

---

build.sbt
core/src/main/scala/com/banno/vault/Vault.scala
core/src/main/scala/com/banno/vault/transit/Transit.scala
core/src/test/scala/com/banno/vault/VaultSpec.scala
core/src/test/scala/com/banno/vault/transit/MockTransitService.scala
core/src/test/scala/com/banno/vault/transit/TransitSpec.scala

This is branched off of the MUnit branch so #164 should be merged first.  @ChristopherDavenport I'd love some looking over this for the Http4s changes, just in case there are better ways to do some of this.  
We'll of course need a new major version for this as well when we release. 
This fixes: https://github.com/Banno/vault4s/issues/166

Cats-Effect-3 Upgrade (Http4s)

---

build.sbt
project/plugins.sbt

Finishes: https://github.com/Banno/vault4s/issues/184

Move from tut to mdoc as tut is going away (7.x and forward)

---

core/src/main/scala/com/banno/vault/Vault.scala
core/src/main/scala/com/banno/vault/models/VaultKeys.scala
core/src/test/scala/com/banno/vault/VaultSpec.scala

Uses GET version with query param list=true vs using LIST http method.
https://www.vaultproject.io/api-docs#api-operations
https://www.vaultproject.io/api/secret/kv/kv-v1#list-secrets
related https://github.com/Banno/vault4s/pull/207

add list secrets functionality, which returns keys given a path

---

.github/workflows/ci.yml
build.sbt
core/src/main/scala/com/banno/vault/Vault.scala
core/src/main/scala/com/banno/vault/models/VaultKeys.scala
core/src/test/scala/com/banno/vault/VaultSpec.scala
project/build.properties
project/plugins.sbt

This was the original merge forward + the fix for the issue we found with https://github.com/Banno/vault4s/pull/218 that was preventing the original from actually working correctly.

Series 7.x to 8.x.  

---

.github/workflows/ci.yml
build.sbt
core/src/main/scala/com/banno/vault/Vault.scala
core/src/main/scala/com/banno/vault/transit/models.scala
core/src/test/scala/com/banno/vault/VaultArbitraries.scala
core/src/test/scala/com/banno/vault/VaultSpec.scala
core/src/test/scala/com/banno/vault/transit/TransitSpec.scala
project/plugins.sbt

This merges series/8.x into main which finishes the merge forward.  This adds the new vault secretList method into main as well as Scala 3 support.  
When building 2.13 ran into evidenceParam issues where Temporal and Concurrent were fighting to suffice for an implicit.

Merge forward: series/8.x to main

---

build.sbt
core/src/test/scala/com/banno/vault/MissingPieces.scala
core/src/test/scala/com/banno/vault/VaultSpec.scala

This is bigger than it should have been after #223, but I haven't forensically examined why.

8.x to main

---

project/plugins.sbt

Update sbt-mdoc to 2.2.22

---

core/src/main/scala/com/banno/vault/Vault.scala
core/src/test/scala/com/banno/vault/VaultSpec.scala

Adds a `loginKubernetes` with a parameterized mount point for the k8s auth method.  The name changes for bincompat's sake, so `kubernetesLogin` is deprecated.

Parameterize the Kubernetes mount point

---

.github/workflows/ci.yml
build.sbt

- http4s-0.22.0 (this is the visible one)
- munit-0.7.27
- Scala-3.0.1

Upgrade dependencies for 8.x

---

build.sbt

I missed it this morning, and it's 0.0.1 louder.

http4s-0.21.1

---

build.sbt
core/src/main/scala/com/banno/vault/Vault.scala
core/src/test/scala/com/banno/vault/VaultSpec.scala
project/plugins.sbt

~~Some of the asynchronous testing was lost in a merge.  I'll bring that back in a separate commit, but this should be sufficient to ship 9.0.0 with CE3 support.~~ Nah, ported that forward, too.

Merge 8.0.0 into 9

---

.git-blame-ignore-revs
.github/workflows/ci.yml
.scalafmt.conf
build.sbt
core/src/main/scala/com/banno/vault/Vault.scala
core/src/main/scala/com/banno/vault/models/CertificateData.scala
core/src/main/scala/com/banno/vault/models/CertificateRequest.scala
core/src/main/scala/com/banno/vault/models/VaultKeys.scala
core/src/main/scala/com/banno/vault/models/VaultRequestError.scala
core/src/main/scala/com/banno/vault/models/VaultSecret.scala
core/src/main/scala/com/banno/vault/models/VaultSecretRenewal.scala
core/src/main/scala/com/banno/vault/models/VaultToken.scala
core/src/main/scala/com/banno/vault/transit/Base64.scala
core/src/main/scala/com/banno/vault/transit/Transit.scala
core/src/main/scala/com/banno/vault/transit/models.scala
core/src/test/scala/com/banno/vault/MissingPieces.scala
core/src/test/scala/com/banno/vault/VaultArbitraries.scala
core/src/test/scala/com/banno/vault/VaultSpec.scala
core/src/test/scala/com/banno/vault/transit/MockTransitService.scala
core/src/test/scala/com/banno/vault/transit/ModelsSpec.scala
core/src/test/scala/com/banno/vault/transit/TransitGenerators.scala
core/src/test/scala/com/banno/vault/transit/TransitSpec.scala
docs/docs/index.md
project/build.properties
project/plugins.sbt

All the PRs are broken because Jekyll bitrotted.  The motivator here is to switch to Laika, but it's a good decrufting in general.

Switch to sbt-typelevel

---

build.sbt

bump tlBaseVersion

---

core/src/test/scala/com/banno/vault/VaultSpec.scala

Not sure how this snuck in, but the PR passed CI and then broke deploy 🤦🏻

Remove unused import

---

core/src/main/scala/com/banno/vault/Vault.scala
core/src/main/scala/com/banno/vault/VaultClient.scala
core/src/test/scala/com/banno/vault/MockVaultService.scala
core/src/test/scala/com/banno/vault/VaultClientSpec.scala

Also updates the documentation to clarify the secret lease situation.

Added readSecretAndKeep
